# Generated by Django 5.2.4 on 2025-07-05 12:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarQuery',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('scraper_name', models.CharField(max_length=100)),
                ('car_make', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarListing',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image_url', models.URLField(max_length=500)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('trim', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(max_length=50)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('mileage', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('transmission', models.CharField(blank=True, max_length=50, null=True)),
                ('fuel_type', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('vehicle_listing_date', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_exit_date', models.CharField(blank=True, max_length=50, null=True)),
                ('seller_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.CharField(max_length=100)),
                ('website_url', models.CharField(max_length=255)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='apps.carquery')),
            ],
        ),
    ]
